services:
  - type: web
    name: quercus-app
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && flask db upgrade
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.12
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: quercus-db
          property: connectionString
      - key: FLASK_SECRET_KEY
        generateValue: true

databases:
  - name: quercus-db
    databaseName: quercus_db
    user: quercusadmin
    plan: free
